version: '3.7'

services:
  backend:
    container_name: youtube_backend
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.backend
    volumes:
      - ./backend/:/backend
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    gunicorn --workers=5 --threads=8 --timeout 1000 backend.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
  frontend:
    container_name: youtube_frontend
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.frontend
    volumes:
      - ./frontend/:/frontend
    ports:
      - "3000:3000"
  db_postgres:
    container_name: postgres_db
    image: postgres
    environment:
        POSTGRES_DB: youtube_db
        POSTGRES_USER: youtubeuser
        POSTGRES_PASSWORD: password
        PGDATA: /data/backend
    volumes:
        - backend:/data/backend
    ports:
        - 5432:5432
    restart: always

volumes:
  backend:
  frontend: